"""book_access

Revision ID: ed75ff2e9cf7
Revises: bcb469013142
Create Date: 2024-03-17 20:30:24.556826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed75ff2e9cf7'
down_revision: Union[str, None] = 'bcb469013142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('access', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'role', ['access'], ['id'])
    op.drop_column('books', 'price')
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'access')
    # ### end Alembic commands ###
